"""Add refresh token fields

Revision ID: d77bf5e46018
Revises: 147690e0ca42
Create Date: 2025-03-09 23:10:49.671828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77bf5e46018'
down_revision: Union[str, None] = '147690e0ca42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('access_tokens', sa.Column('refresh_end_timestamp', sa.DateTime(), nullable=True))
    op.add_column('access_tokens', sa.Column('token_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_access_tokens_refresh_token'), 'access_tokens', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tokens_refresh_token'), table_name='access_tokens')
    op.drop_column('access_tokens', 'token_type')
    op.drop_column('access_tokens', 'refresh_end_timestamp')
    op.drop_column('access_tokens', 'refresh_token')
    # ### end Alembic commands ###
