name: CI

on: 
  pull_request:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run formatter
        run: make fmt.check

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Build the project
        run: make build

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Start Services
        run: |
          docker compose up -d backend postgres
          sleep 10

      - name: Run Postman Collection
        run: |
          newman run $(pwd)/tests/postman_auth_tests.json

      - name: Stop Services
        run: |
          docker compose down

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#        
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: "disk0dancer"
#          password: ""
#          
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: disk0dancer/copilot-api:latest
